openapi: 3.1.0
info:
  title: Annuity Policy Income Activation APIs
  version: "1.0.0"
  description: APIs for managing income activation of policies
  contact:
    name: Katherine Dease
    email: kdease@irionline.org

paths:
  /v1/policyincome:      
    post:
      operationId: postGetPolicyIncomeDetailsByPolicyNumber
      summary: Get Policy Income Activation Details By PolicyNumber.
      description: Get Policy Income Activation Details By PolicyNumber.
      tags:
        - Policy Income Activation
      parameters:
        - $ref: '#/components/parameters/correlationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PolicyIncomeActivationRequest'
      responses:
          "200":
            description: Policy Income Activation retrieved successfully.
            content:
              application/json:
                schema:
                     $ref: '#/components/schemas/PolicyIncomeActivationResponse'
          "400":
            description: Bad Request
          "401":
            description: Unauthorized 
          "404":
            description: Not Found
          "405":
            description: Method Not Allowed
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
          "504":
            description: Gateway Timeout.
components:
  parameters:
    correlationId:
      name: correlationId
      description: Optional custom header to be returned to the caller in response payload
      in: header
      required: false
      schema:
        type: string
  schemas:
    PolicyIncomeActivationRequest:
      description: Schema for policy income activation request
      required: [policyNumber]
      type: object
      properties:
        policyNumber:
          type: string
          examples: 
            - "241235566"
        cusip:
          type: string
          examples: 
            - "037833100"
    PolicyIncomeActivationResponse:
      type: object
      properties:
        policyNumber:
          type: string
          examples: 
            - "241235566"
        isIncomeRiderActivated:
          type: boolean
        lastPaymentDate:
          type: string
          format: date
          examples: 
            - "2024-03-11"
        netPaymentAmount:
          type: number
          format: float
          examples: 
            - 5000.00
        grossPaymentAmount:
          type: number
          format: float
          examples: 
            - 2500.00
        paymentsPerYear:
          type: integer
          min: 1
          max: 365
          examples: 
            - 24
        cusip:
          type: string
          examples: 
            - "037833100"
        incomeType:
          type: string
          enum:
            - annuitized
            - incomeRiders
            - scheduledPayments
            - rmd
