openapi: 3.1.0
info:
  title: Annuity Policy Income Activation APIs
  version: "1.0.0"
  description: APIs for managing income activation of policies
paths:
  /v1/policies/{policyNumber}/income-activation:      
    get:
      operationId: getPolicyIncomeActivationByPolicyNumber
      summary: Get Policy Income Activation By PolicyNumber.
      description: Get Policy Income Activation By PolicyNumber.
      tags:
        - Policy Income Activation
      parameters:
        - $ref: '#/components/parameters/policyNumber'
        - $ref: '#/components/parameters/cusip'
        - $ref: '#/components/parameters/correlationId'
      responses:
          "200":
            description: Policy Income Activation retrieved successfully.
            content:
              application/json:
                schema:
                     $ref: '#/components/schemas/PolicyIncomeActivationResponse'
          "400":
            description: Bad Request
          "401":
            description: Unauthorized 
          "404":
            description: Not Found
          "405":
            description: Method Not Allowed
          "500":
            description: Internal Server Error
          "503":
            description: Service Unavailable
          "504":
            description: Gateway Timeout.
components:
  parameters:
    policyNumber:
      name: policyNumber
      description: Required path parameter for the policy number to be retrieved
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/policyNumber'
    cusip:
      name: cusip
      description: Optional query parameter for the CUSIP
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/cusip'
    correlationId:
      name: correlationId
      description: Optional custom header to be returned to the caller in response payload
      in: header
      required: false
      schema:
        type: string
  schemas:
    cusip:
      type: string
      minLength: 9
      maxLength: 9
      pattern:  ^[0-9]{3}[A-Z0-9]{5}[0-9]$
    policyNumber:
      type: string
      minLength: 1
      maxLength: 30
    PolicyIncomeActivationResponse:
      description: Schema for policy income activation data
      type: object
      required: [policyNumber, isIncomeRiderActivated]
      properties:
        policyNumber:
          $ref: '#/components/schemas/policyNumber'
        isIncomeRiderActivated:
          type: boolean
        lastPaymentDate:
          type: string
          format: date
          examples: 
            - "2024-03-11"
        netPaymentAmount:
          type: number
          format: float
          examples: 
            - 5000.00
        grossPaymentAmount:
          type: number
          format: float
          examples: 
            - 2500.00
        paymentsPerYear:
          type: integer
          minimum: 1
          maximum: 365
          examples: 
            - 24
        cusip:
          type: string
          examples: 
            - "037833100"
        incomeType:
          type: string
          enum:
            - annuitized
            - incomeRiders
            - scheduledPayments
            - rmd
