openapi: 3.1.0

info:
  title: Producer Training APIs
  description: |
    APIs enabling training vendors, carriers, and distributors to transmit
    producer training completion information.
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/Insured-Retirement-Institute/Pending-Case/blob/main/LICENSE

tags:
  - name: Producer Training Update
    description: Endpoints related to real-time updates into training statuses.

paths:
  /v1/producer-trainings:
    post:
      tags:
        - Producer Training Update
      summary: Submit producer training completion information
      description: Creates or updates producer training records.
      parameters:
        - name: correlationId
          in: header
          required: false
          description: Optional correlation ID for request tracing
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProducerTrainingRequest'
      responses:
        '201':
          description: Training update created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProducerTrainingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

components:

  schemas:

    ProducerTrainingRequest:
      type: object
      description: Producer training submission payload
      required:
        - producer
        - courses
      properties:
        producer:
          $ref: '#/components/schemas/Producer'
        courses:
          type: array
          minItems: 1
          maxItems: 12
          items:
            $ref: '#/components/schemas/Course'

    Producer:
      type: object
      description: Licensed producer information
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
          minLength: 1
          maxLength: 105
          pattern: '^[A-Za-z\s''\-]{1,105}$'
        middleName:
          type: string
          minLength: 1
          maxLength: 105
          pattern: '^[A-Za-z\s''\-]{1,105}$'
        lastName:
          type: string
          minLength: 1
          maxLength: 105
          pattern: '^[A-Za-z\s''\-]{1,105}$'
        npn:
          type: string
          minLength: 5
          maxLength: 10
          pattern: '^\d+$'
        crdNumber:
          type: string
          minLength: 5
          maxLength: 10
          pattern: '^\d+$'
        taxId:
          type: string
          minLength: 9
          maxLength: 9
          pattern: '^\d{9}$'

    Course:
      type: object
      description: Training course details
      required:
        - provider
        - id
        - name
        - type
        - trainingCompletionDate
      properties:
        provider:
          type: string
          enum:
            - adBanker
            - kaplan
            - luma
            - pinpoint
            - questCE
            - reged
            - successCE
            - iCapital
            - smartPros
            - webCE
        id:
          type: string
          minLength: 1
          maxLength: 20
        name:
          type: string
          minLength: 1
          maxLength: 40
        method:
          type: string
          enum:
            - online
            - classroom
            - referenceMaterials
            - wholesaler
        type:
          type: string
          enum:
            - state
            - product
            - bestInterest
            - disability
            - longTermCare
            - rider
            - ethics
            - antiMoneyLaundering
        originatingJurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
        originatingJurisdictionCreditHours:
          type: number
          minimum: 1
          maximum: 999
        reciprocityJurisdictions:
          type: array
          items:
            $ref: '#/components/schemas/ReciprocityJurisdiction'
        cusips:
          type: array
          minItems: 1
          maxItems: 250
          items:
            type: string
            pattern: '^[A-Z0-9]{9}$'
        productTrainingCategory:
          type: string
        trainingCompletionDate:
          type: string
          format: date
        trainingExpirationDate:
          type: string
          format: date

      allOf:
        - if:
            properties:
              type:
                const: product
          then:
            required:
              - cusips
        - if:
            properties:
              type:
                enum:
                  - state
                  - bestInterest
          then:
            required:
              - originatingJurisdiction

    ReciprocityJurisdiction:
      type: object
      required:
        - jurisdiction
      properties:
        jurisdiction:
          $ref: '#/components/schemas/Jurisdiction'
        creditHours:
          type: number
          minimum: 1
          maximum: 999

    Jurisdiction:
      type: string
      enum:
        - AL
        - AK
        - AZ
        - AR
        - CA
        - CO
        - CT
        - DE
        - DC
        - FL
        - GA
        - GU
        - HI
        - ID
        - IL
        - IN
        - IA
        - KS
        - KY
        - LA
        - ME
        - MD
        - MA
        - MI
        - MN
        - MS
        - MO
        - MT
        - NE
        - NV
        - NH
        - NJ
        - NM
        - NY
        - NC
        - ND
        - OH
        - OK
        - OR
        - PA
        - PR
        - RI
        - SC
        - SD
        - TN
        - TX
        - UT
        - VT
        - VI
        - VA
        - WA
        - WV
        - WI
        - WY

    ProducerTrainingResponse:
      type: object
      required:
        - status
      properties:
        correlationId:
          type: string
          description: Correlation ID echoed from the request

    Error:
      type: object
      required:
        - errorCode
        - errorMessage
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
        correlationId:
          type: string
          description: Correlation ID echoed from the request

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Authorization failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    PayloadTooLarge:
      description: Payload too large
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnsupportedMediaType:
      description: Unsupported media type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    TooManyRequests:
      description: Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ServiceUnavailable:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
